---
# Docker installation steps
- name: Packages installation
  action: apt pkg="{{item}}" state=installed
  with_items:
    - apt-transport-https
    - ca-certificates
    - gnupg-agent
    - software-properties-common

# apt_key module is not used as python 2.7.6 is not accepting SNI based https sites
- name: Add Docker APT key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Add Docker CE repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install Docker
  action: apt pkg="{{item}}" state=installed
  with_items:
    - docker-ce

- copy:
    src: 05.update-docker.sh
    dest: "{{cloud_user_script_path}}/"
    mode: 0755
